### ISSUE TITLE
Non-Illumina reads

### ISSUE THREAD

**Issue by AntonMatiiv** [CFSAN-Biostatistics/shigatyper#2]
Hi! Is it possible to use shigatyper for non-Illumina reads? For example, MGISEQ reads.

**Comment by florathecat** [comment]
Hi Anton, Thanks for your message. shigatyper reads paired-end fastq files so I imagine it should read MGISEQ reads. However if you only have single-end reads the script needs to be tweaked.

**Comment by AntonMatiiv** [comment]
Thank you very much for your answer!

**Comment by rpetit3** [comment]
Hi @AntonMatiiv

v2 of Shigatyper now supports Single-end and Nanopore reads

Cheers
