### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by erinyoung** [CFSAN-Biostatistics/shigatyper#3]
I would like to put this useful tool in a docker container. 

Right now I'm using the anaconda license (since that is what the conda package links to), but it'd make me feel better if you added a license to this repository.

**Comment by crashfrog** [comment]
Hi Young,

As a work product of the Federal government this software is in the US public domain; we can’t assign license to it by Federal law.

Justin

**Comment by rpetit3** [comment]
Would this work? https://github.com/CFSAN-Biostatistics/snp-pipeline/blob/master/LICENSE.txt or this one https://github.com/CFSAN-Biostatistics/SeroTools/blob/master/LICENSE

**Comment by rpetit3** [comment]
@erinyoung Should be good to go now with v2 of Shigatyper

**Comment by erinyoung** [comment]
@rpetit3 Thanks! 

@jwarnn is way ahead of me! https://github.com/StaPH-B/docker-builds/pull/321
