### ISSUE TITLE
Help: Two types of value errors

### ISSUE THREAD

**Issue by wolthuisr** [CFSAN-Biostatistics/shigatyper#4]
Hello,

First of all, thank you for making this tool! I am analyzing a big dataset, but two of my samples each give a different value error.

1) ValueError: invalid literal for int() with base 10: '\n'. It occurs in line 558 of shigatyper.py
2) ValueError: list.remove(x): x not in list. This one occurs in line 599 of shigatyper.py

Could you please tell me if this problem is caused by the samples or if this needs to be fixed in the tool.

If it is helpful I can send extra log files through the mail. I hope someone can help me out on this one!

Kind regards,
Roxanne Wolthuis

**Comment by crashfrog** [comment]
Hi Roxanne,

Thanks for opening the issue. I have the log files you sent along with your email which I'm reviewing. Looks like the second one is a pretty straightforward bug which I've just committed a fix for; if you're running the repository version you should be able to pull the new code. If you're running the conda package we should have a new build in a couple of days (once I remember how to update bioconda.)

Looking at the first issue now, its either a bug or a failure that stems from a change to Samtools. Can you describe your execution environment at all? Are you using the Conda package or the repository version directly?

**Comment by wolthuisr** [comment]
Hi,
I am using your tool as a Conda package with a .yaml file to build the environment(its attached to this comment as a .txt). I am running this on a RHEL linux cluster.

[shigatyper.txt](https://github.com/CFSAN-Biostatistics/shigatyper/files/7303866/shigatyper.txt)

**Comment by wolthuisr** [comment]
Hi Justin,

Do you have any updates on this issue yet? Let me know if I can help in any way.

**Comment by wolthuisr** [comment]
Hi Justin,

I forked the shigatyper repository to fix the current problem. I made some adjustments and I think this fixes the bug... sadly I have only one sample to test it on, but I can make a pull request if you are interested.  You can check out the forked repository in my account.

Roxanne

**Comment by crashfrog** [comment]
Hi Roxanne,

Thanks for your work on this and the helpful comment. I've initiated and accepted a PR so the mainline branch should have your changes, and I'm inviting you as a contributor to the main project too.

**Comment by crashfrog** [comment]
Updated the recipe in Bioconda-recipes, so pending approval, there should be a Shigatyper 1.0.7 package pretty soon.

**Comment by wolthuisr** [comment]
Thanks, I will close the issue!
